// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/home/index.vue')['default']
    HomeContent: typeof import('./src/components/home/content/index.vue')['default']
    HomeSearch: typeof import('./src/components/home/search/index.vue')['default']
    IconIcon: typeof import('./src/components/icon/icon.vue')['default']
    Play: typeof import('./src/components/play/index.vue')['default']
    PlayContent: typeof import('./src/components/play/content/index.vue')['default']
    PlayContentLyric: typeof import('./src/components/play/content/lyric/index.vue')['default']
    PlayContentPoster: typeof import('./src/components/play/content/poster/index.vue')['default']
    PlayControl: typeof import('./src/components/play/control/index.vue')['default']
    PlayHeader: typeof import('./src/components/play/header/index.vue')['default']
    PlaySlideBar: typeof import('./src/components/play/slide-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/slide/index.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
  }
}
